# Generated by Django 5.1.7 on 2025-03-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('thematic', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('value', models.FloatField()),
                ('published_date', models.DateField()),
            ],
        ),
    ]
